CREATE VIEW [dbo].[view_PadPoliceInfo]
AS
SELECT   PATIENT_ID, PATIENT_NAME, TREATMENT_ID, POLICE_TYPE, POLICE_TITLE, POLICE_DESCRIPTION, STATE, 
                CREATE_USER_ID, CREATE_USER_NAME, CREATE_AT, CENT_ID, INST_ID
FROM      HDIS_DEV.dbo.HD_TREATMENT_POLICE
WHERE   (STATE = 1)