create view [dbo].[view_PatientBasicTreatInfo]
 as

select TREATMENT.PATIENT_ID,TREATMENT.ID as TREATMENT_ID, TREATMENT.CENT_ID,TREATMENT.TRAETMENT_DATE,
TREATMENT.TREATMENT_MODE, TREATMENT.DIALYZER_NAME, TREATMENT.ATICOAGULANT_NAME, TREATMENT.FIRST_DOSE, TREATMENT.KEEP_DOSE, TREATMENT.DIALYSATE_NAME,
TREATMENT.BEFORE_WEIGHT, TREATMENT.DRY_WEIGHT, TREATMENT.BEFORE_SBP, TREATMENT.BEFORE_SP,
TREATMENT.BEFORE_HR, TREATMENT.BEFORE_TEMPERATURE, TREATMENT.PRESET_UF, TREATMENT.ACTUAL_UF, TREATMENT.DEFAULT_TREAT_TIME,
TREATMENT.AFTER_WEIGHT,  TREATMENT.AFTER_SBP, TREATMENT.AFTER_SP,
TREATMENT.AFTER_HR, TREATMENT.AFTER_TEMPERATURE
from [HDIS_DEV].[dbo].[HD_PATIENT] patient
join [HDIS_DEV].[dbo].HD_TREATMENT TREATMENT
on patient.ID = TREATMENT.PATIENT_ID