CREATE VIEW [dbo].[view_PadPoliceInfo]
AS
SELECT   ID,PATIENT_ID, PATIENT_NAME, TREATMENT_ID, POLICE_TYPE, POLICE_TITLE, POLICE_DESCRIPTION, STATE, 
                CREATE_USER_ID, CREATE_USER_NAME, CREATE_AT, CENT_ID, INST_ID, [PATIENT_AGE], [PATIENT_SEX], [BED_LABEL], [CLASS_NAME],(select stuff((select ';' + [FILE_NAME] from  HDIS_DEV.dbo.[HD_FILE_MASTER]  where EXTERNAL_ID=h.ID and EXTERNAL_CODE='0019' for xml path('')),1,1,'') ) as FILE_INFO
FROM      HDIS_DEV.dbo.HD_TREATMENT_POLICE h
WHERE   (STATE = 1)